// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
//
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3J8HyYRUGid1XhX2LsMlovKhbfwd54c',
    appId: '1:370503222428:web:c90667a0bbeed24ef51959',
    messagingSenderId: '370503222428',
    projectId: 'myecommerceapp-d43ed',
    authDomain: 'myecommerceapp-d43ed.firebaseapp.com',
    storageBucket: 'myecommerceapp-d43ed.appspot.com',
    measurementId: 'G-B5S02F7NBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVyk5gPjDlkdzzKf0Ag1mwsuOlj9myE8',
    appId: '1:370503222428:android:11de89d5f40a46d5f51959',
    messagingSenderId: '370503222428',
    projectId: 'myecommerceapp-d43ed',
    storageBucket: 'myecommerceapp-d43ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwWVCk_Hz6INDch2eUj_EEdSdRSCdist8',
    appId: '1:370503222428:ios:ba07b0621ba8abd1f51959',
    messagingSenderId: '370503222428',
    projectId: 'myecommerceapp-d43ed',
    storageBucket: 'myecommerceapp-d43ed.appspot.com',
    iosClientId: '370503222428-gl49br4iie8pas88r6ou9clcak4adfjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwWVCk_Hz6INDch2eUj_EEdSdRSCdist8',
    appId: '1:370503222428:ios:8eed94acda3b8172f51959',
    messagingSenderId: '370503222428',
    projectId: 'myecommerceapp-d43ed',
    storageBucket: 'myecommerceapp-d43ed.appspot.com',
    iosClientId: '370503222428-rr5m1rfh9icmoqao8esv54ch6bt04bqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionstore.RunnerTests',
  );
}
